version: "3.8"

services:
  postgres:
    image: postgres
    volumes:
      - ./postgres-moody:/var/lib/postgresql/data # Change the volume path here
    environment:
      POSTGRES_DB: moody
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres

  moody-web:
    image: moody-django
    build: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    restart: always
    env_file:
      - .env.dev
    volumes:
      - ".:/app/"
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: moody
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
    depends_on:
      - postgres

  shell:
    image: moody-django
    build: .
    command: sh -c "python manage.py shell"
    env_file:
      - .env.dev
    volumes:
      - ".:/app/"
    environment:
      POSTGRES_DB: moody
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
    depends_on:
      - postgres

volumes:
  postgres-bug-busters:
